package copier

import (
	"bytes"
	"log"
	"os"
	"strings"
	"testing"
)

func TestFormatTablePlan(t *testing.T) {
	table := tableMeta{
		Schema:     "dbo",
		Name:       "orders",
		ApproxRows: 1234,
		Columns: []columnMeta{
			{Name: "id", Copyable: true},
			{Name: "payload", Copyable: true},
			{Name: "rv", Copyable: false, SkipReason: "rowversion is regenerated by SQL Server"},
		},
		CopyColumns: []columnMeta{
			{Name: "id", Copyable: true},
			{Name: "payload", Copyable: true},
		},
		HasIdentity: true,
		BulkOK:      false,
		BulkReason:  "column payload uses unsupported bulk type xml",
	}

	got := formatTablePlan(table, true)
	wants := []string{
		"[dbo].[orders]",
		"rows~1234",
		"columns=2/3 copyable",
		"mode=row-insert",
		"drop target table if present",
		"identity insert",
		"bulk fallback: column payload uses unsupported bulk type xml",
	}
	for _, want := range wants {
		if !strings.Contains(got, want) {
			t.Fatalf("expected %q in plan line %q", want, got)
		}
	}
}

func TestPrintPlanViewsOnly(t *testing.T) {
	oldStdout := os.Stdout
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatalf("pipe: %v", err)
	}
	os.Stdout = w
	defer func() {
		os.Stdout = oldStdout
	}()

	oldLog := log.Writer()
	log.SetOutput(&bytes.Buffer{})
	defer log.SetOutput(oldLog)

	c := &copier{
		cfg: config{SourceDSN: "src", TargetDSN: "dst"},
		views: []viewMeta{{
			Schema:    "reporting",
			Name:      "daily_sales",
			DependsOn: []string{"[reporting].[base_sales]"},
		}},
	}
	c.printPlan()
	_ = w.Close()

	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		t.Fatalf("read plan output: %v", err)
	}

	got := out.String()
	if !strings.Contains(got, "views selected: 1") {
		t.Fatalf("expected views count in plan output, got:\n%s", got)
	}
	if !strings.Contains(got, "Views") || !strings.Contains(got, "[reporting].[daily_sales]") {
		t.Fatalf("expected view listing in plan output, got:\n%s", got)
	}
	if strings.Contains(got, "No tables matched") {
		t.Fatalf("unexpected tables-only empty message in views-only plan:\n%s", got)
	}
}

func TestPrintPlanSequencesAndProcedures(t *testing.T) {
	oldStdout := os.Stdout
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatalf("pipe: %v", err)
	}
	os.Stdout = w
	defer func() {
		os.Stdout = oldStdout
	}()

	oldLog := log.Writer()
	log.SetOutput(&bytes.Buffer{})
	defer log.SetOutput(oldLog)

	c := &copier{
		cfg:        config{SourceDSN: "src", TargetDSN: "dst"},
		aliasTypes: []aliasTypeMeta{{Schema: "sales", Name: "order_code", SystemTypeName: "nvarchar", Nullable: true}},
		tableTypes: []tableTypeMeta{{Schema: "sales", Name: "order_line_type", Columns: []columnMeta{{Name: "order_id", SystemTypeName: "int", Nullable: false}}}},
		sequences:  []sequenceMeta{{Schema: "seq", Name: "order_seq", RestartWith: "110", Increment: "5"}},
		functions:  []functionMeta{{Schema: "app", Name: "count_orders", DependsOn: []string{"[app].[base_count]"}}},
		procedures: []procedureMeta{{Schema: "app", Name: "sync_orders", DependsOn: []string{"[app].[orders_alias]", "[app].[count_orders]"}}},
		triggers:   []triggerMeta{{Schema: "app", Name: "trg_sync_orders", TableSchema: "sales", TableName: "orders", Disabled: true, DependsOn: []string{"[app].[sync_orders]", "[app].[orders_alias]"}}},
		synonyms:   []synonymMeta{{Schema: "app", Name: "orders_alias", BaseObjectName: "[sales].[orders]"}},
	}
	c.printPlan()
	_ = w.Close()

	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		t.Fatalf("read plan output: %v", err)
	}

	got := out.String()
	wants := []string{
		"alias types selected: 1",
		"table types selected: 1",
		"sequences selected: 1",
		"functions selected: 1",
		"procedures selected: 1",
		"triggers selected: 1",
		"synonyms selected: 1",
		"Alias Types",
		"[sales].[order_code] | base=nvarchar | null",
		"Table Types",
		"[sales].[order_line_type] | columns=1",
		"Sequences",
		"[seq].[order_seq] | restart with=110 | increment=5",
		"Functions",
		"[app].[count_orders] | depends on: [app].[base_count]",
		"Procedures",
		"[app].[sync_orders] | depends on: [app].[orders_alias], [app].[count_orders]",
		"Triggers",
		"[app].[trg_sync_orders] | on [sales].[orders] | disabled | depends on: [app].[sync_orders], [app].[orders_alias]",
		"Synonyms",
		"[app].[orders_alias] | for [sales].[orders]",
	}
	for _, want := range wants {
		if !strings.Contains(got, want) {
			t.Fatalf("expected %q in plan output, got:\n%s", want, got)
		}
	}
}
